### ISSUE TITLE
Another Eisenstein series

### ISSUE THREAD

**Issue by ahorawa** [edgarcosta/hilbertmodularforms#189]
Another Eisenstein series didn't compute, because can't recognize embedding correctly.
I ran:
```
F:=QuadraticField(5);
prec:=20;
M:=GradedRingOfHMFs(F, prec);
ZF:=Integers(F);
N:= 31*ZF;
H := HeckeCharacterGroup(N, [1,2]);
chi := H.1*H.2^7;
IsCompatibleWeight(chi, 1);
SetVerbose("HilbertModularForms", 3);
Mchi := HMFSpace(M, N, [1,1], chi^(-1));
EisensteinBasis(Mchi);
```
and got:
```
true

EisensteinBasis(
Mk: Space of Hilbert modular forms over Quadratic Field with def...
)
EisensteinInclusions(
Mk: Space of Hilbert modular forms over Quadratic Field with def...,
eta: 1,
psi: $.1*$.2^23
)
EisensteinCoefficients(
M: Graded ring of Hilbert modular forms over Quadratic Field wi...,
Weight: [ 1, 1 ],
eta: 1,
psi: $.1*$.2^23,
ideals: [ Zero Principal Ideal Generator: 0, Principal Ideal Generat...
)
LValue_Recognized(
M: Graded ring of Hilbert modular forms over Quadratic Field wi...,
k: 1,
psi: $.1*$.2^23
)
In file "/Users/alexh/Documents/Michigan/mathematics/Computations/HMS/hilbertmodularforms/ModFrmHilD/Creation/EisensteinSeries.m", line 196, column 7:
>>       assert #places ge 1;
         ^
Runtime error in assert: Assertion failed
```

**Comment by jvoight** [comment]
I think the issue is in line 189
`    places := InfinitePlaces(CoefficientField);`
We meant to loop over all *embeddings* of the coefficient field.  The difference is complex conjugation at each complex place.

**Comment by jvoight** [comment]
I fixed this, but am throwing it away, because there is a better approach.  

The complex embedding that is chosen in the Hecke Grossencharacter code has a designated element which is a root of unity sent to e^(2*pi*i/n) where n is the order.  We can do the same with our zeta, we just choose the embedding which is compatible with this choice.

If we want a safety check: compute 
`'@'(pp,chi : Raw)`
to get an integer r which is considered modulo the integer n defined by
`Modulus(Parent('@'(pp,chi : Raw)))`
to get chi(pp) = exp(2*pi*i*r/n).
