### ISSUE TITLE
elements.m '/' division has type issues

### ISSUE THREAD

**Issue by ldsgsm** [edgarcosta/hilbertmodularforms#48]
If I try to compute g/f, where g has integer coefficients and f has rational coefficients, the division intrinsic returns an error.

**Comment by jvoight** [comment]
We need automatic coercion in division based on the type of f and g.

**Comment by jvoight** [comment]
Since so much of our functionality uses linear algebra (over QQ), I think we should always return an object with coefficients in a field.  If the user divides two things with entries in a ring, the operation of returning the "integral" quotient is a different operation than the quotient.  For example, if we divide 5 by 3, everyone would say the answer is the rational number 5/3; if instead we divide 6 by 3, for consistency the answer should be the rational number 6/3 = 2.  If you know for some reason that this quotient has integral coefficients, this coercion should happen outside the function.
