### ISSUE TITLE
Loading config twice = Seg fault

### ISSUE THREAD

**Issue by edgarcosta** [edgarcosta/hilbertmodularforms#77]
```
$ magma
Magma V2.24-4     Tue May 21 2019 14:03:12 on omicron  [Seed = 2903887063]

+-------------------------------------------------------------------+
|       This copy of Magma has been made available through a        |
|                   generous initiative of the                      |
|                                                                   |
|                         Simons Foundation                         |
|                                                                   |
| covering U.S. Colleges, Universities, Nonprofit Research entities,|
|               and their students, faculty, and staff              |
+-------------------------------------------------------------------+

Type ? for help.  Type <Ctrl>-D to quit.

Loading startup file "/Users/edgarcosta/.magmarc"

> load "config.m";
Loading "config.m"
> load "config.m";
Loading "config.m"


Magma: Internal error

Please mail this entire run [*** WITH THE DETAILS BELOW ***]
    to magma-bugs@maths.usyd.edu.au

You can print the entire input by entering:
%P

Version: 2.24-4
Machine type: intel64-osx
Initial seed: 2903887063
Time to this point: 0.33
Memory usage: 32.09MB
Segmentation fault
```

**Comment by michaelmusty** [comment]
It looks like this is caused by attaching the file Elements.m

$ magma 
Magma V2.24-3     Tue May 21 2019 14:28:35 on eleanor  [Seed = 145758002]

+-------------------------------------------------------------------+
|       This copy of Magma has been made available through a        |
|                   generous initiative of the                      |
|                                                                   |
|                         Simons Foundation                         |
|                                                                   |
| covering U.S. Colleges, Universities, Nonprofit Research entities,|
|               and their students, faculty, and staff              |
+-------------------------------------------------------------------+

Type ? for help.  Type <Ctrl>-D to quit.
> Attach("ModFrmHilD/Elements.m");
> Attach("ModFrmHilD/Elements.m");


Magma: Internal error

Please mail this entire run [*** WITH THE DETAILS BELOW ***]
    to magma-bugs@maths.usyd.edu.au

You can print the entire input by entering:
%P

Version: 2.24-3
Machine type: intel64-linux
Initial seed: 145758002
Time to this point: 0.04
Memory usage: 32.09MB
Segmentation fault
